### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by norpan** [danyx23/elm-uuid#13]
Hi,
are you working on migrating this to Elm 0.19? Do you want a PR?

**Comment by danyx23** [comment]
I would be happy for prs, am traveling a lot at the moment and have little time for updates. Thanks!

**Comment by jgrenat** [comment]
@danyx23 I've started migrating this, but I am currently stuck because we need to wait for elm-community/shrink to be ported to Elm 0.19 in order for Fuzz.custom to be used.

See https://github.com/elm-explorations/test/issues/15

**Comment by norpan** [comment]
There is no need for custom fuzzers, since it uses the standard Random now. #14 works and passes all tests.

**Comment by jgrenat** [comment]
My bad, I hadn't seen your PR! 😝
