### ISSUE TITLE
Nil UUID

### ISSUE THREAD

**Issue by janslifka** [danyx23/elm-uuid#16]
In some cases, you need to use an empty value (such as Nothing, empty string or list, etc.). There is a nil/empty UUID value [1], however, there is no simple way to create one using the library. It would be nice to have a simple function to create one.

```
nil : Uuid
nil =
    Uuid "00000000-0000-0000-0000-000000000000"
```

[1] https://www.uuidgenerator.net/version-nil

**Comment by danyx23** [comment]
This package has now been superseded by https://package.elm-lang.org/packages/NoRedInk/elm-uuid/2.0.0/ I'm sure you can submit a PR there to add this.
